Magazin/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('telefon.urls')),
    path('users/',include('users.urls')),
    path('laptop/',include('laptop.urls')),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

telefon/urls.py
from django.urls import path
from  . import views


urlpatterns = [
    path('', views.telefon),
    path('about', views.about),
    path('search', views.search, name='search'),
    path('cos', views.cos),
    path('add_to_cart/<int:phone_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:phone_id>/', views.remove_to_cart, name='remove_to_cart'),
    
    path('checkout/', views.checkout, name='checkout'),
    path('success/', views.success, name='success'),
    
]

users/urls.py
from django.urls import path


urlpatterns = [
    

]

telefon/models.py
from django.db import models
from users.models import CustomUser
from decimal import Decimal
from django.utils import timezone


class Telefon(models.Model):
    model = models.CharField(max_length=200)
    anul = models.DateTimeField(auto_now_add=True)
    producator = models.CharField(max_length=200)
    procesor = models.CharField(max_length=30)
    descriere = models.TextField()
    price = models.FloatField()

    
    def __str__(self):
        return f" {self.model} {self.producator}"
    
    
class Images(models.Model):
    image = models.ImageField(upload_to='telefon/', max_length=300, null=True, default='')
    telefon = models.ForeignKey(Telefon, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.telefon}"
    
    
class CartItem(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    telefon = models.ForeignKey(Telefon, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.telefon.model} - {self.quantity}"
    
class Payment(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    cart = models.ManyToManyField(CartItem)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    payment_date = models.DateTimeField(default=timezone.now)  

    def __str__(self):
        return f"Payment {self.id} by {self.user.username}"


    

telefon/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from .documents import TelefonDocument
from .models import Telefon, CartItem, Payment
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import json
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from elasticsearch_dsl.query import MultiMatch, Wildcard


@cache_page(60*5, cache='default')
def telefon(request):
    telefons = Telefon.objects.all()
    template = loader.get_template('home.html')
    context = {
        'telefons': telefons,
    }
    return HttpResponse(template.render(context, request))


def about(request):
    return render(request, 'about.html')


def search(request):
    q = request.GET.get("q")
    context = {}
    if q:
        s = TelefonDocument.search().query(
            MultiMatch(query=q, fields=['model', 'producator', 'procesor', 'descriere'], fuzziness='AUTO')
            |
            Wildcard(model=q.lower() + '*')
            |
            Wildcard(producator=q.lower() + '*')
            |
            Wildcard(procesor=q.lower() + '*')
            |
            Wildcard(descriere=q.lower() + '*')
        )
        context["telefons"] = s.to_queryset()
    else:
        context["telefons"] = Telefon.objects.all()
    return render(request, 'home.html', context)






def cos(request):
    user_id = request.user.id
    cache_key = f'cart_items_{user_id}'
    cart_items = cache.get(cache_key)
    
    if cart_items is None:
        cart_items = list(CartItem.objects.filter(user=request.user))
        cache.set(cache_key, cart_items, 900)  # 900 seconds
    
    return render(request, 'cos.html', {'cart_items': cart_items})


def add_to_cart(request, phone_id):
    telefon = get_object_or_404(Telefon, id=phone_id)
    cart_item, created = CartItem.objects.get_or_create(user=request.user, telefon=telefon)

    if not created:
        cart_item.save()
        
    user_id = request.user.id
    cache_key = f'cart_items_{user_id}'
    
    # Invalidează cache-ul pentru utilizatorul respectiv
    cache.delete(cache_key)
    
    return JsonResponse({'status': 'success'})

def remove_to_cart(request, phone_id):
    telefon = get_object_or_404(Telefon, id=phone_id)
    
    cart_item = CartItem.objects.filter(user=request.user, telefon=telefon).first()
    
    if cart_item:
        cart_item.delete()
        
        # Invalidează cache-ul pentru utilizatorul respectiv
        user_id = request.user.id
        cache_key = f'cart_items_{user_id}'
        cache.delete(cache_key)
        
        return HttpResponse(status=200) 
    else:
        return JsonResponse({'error': 'Elementul nu a fost găsit în coș.'}, status=404)
    


@login_required
@csrf_exempt
def checkout(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        selected_items = data.get('selected_items', [])

        if not selected_items:
            return JsonResponse({'error': 'Nu s-au selectat produse pentru plată.'}, status=400)

        total_price = sum(float(item['totalPrice']) for item in selected_items)
        item_ids = [item['itemId'] for item in selected_items]  # Colectăm item.id-urile

        cart_items = CartItem.objects.filter(id__in=item_ids)

        if cart_items.exists():
            payment = Payment.objects.create(user=request.user, total_price=total_price)
            payment.cart.set(cart_items)  # Adăugăm item.id-urile în câmpul ManyToMany
            cart_items.delete()
            
            user_id = request.user.id
            cache_key = f'cart_items_{user_id}'
            cache.delete(cache_key)
        

            return JsonResponse({'success': 'Plata a fost efectuată cu succes!'})
        
        return JsonResponse({'error': 'Produsele selectate nu există în coș.'}, status=400)

    return JsonResponse({'error': 'Metoda de request trebuie să fie POST.'}, status=405)


def success(request):
    return render(request, 'success.html')
    

telefon/templates/about.html
<!-- about.html -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/magazin/about.css' %}">
</head>
<body>
    <header>
        <h1>About</h1>
        {% include 'header.html' %}
    </header>

    <div>
        <p>Producător: </p>
        <p class="details-descriere">Descriere:</p>
        <p class="item-price">Price: €</p>
    </div>
    

    <footer>
        {% include 'footer.html' %}
    </footer>
</body>
</html>

telefon/templates/cos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cosul de Cumparaturi</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/magazin/cart.css' %}">
    <script src="{% static 'js/delete_cart.js' %}"></script>
    <script src="{% static 'js/payment_cart.js' %}"></script>
</head>
<body>
    <header>
        <h1>Cosul de Cumparaturi</h1>
        {% include 'header.html' %}
    </header>

    <div class="container-general">
        <div class="container-cos">
            <div class="Selectet">
                <button class="select-all" onclick="toggleSelectAllItems()"></button> 
                <p>Selectează Toate</p>
            </div>
            {% if cart_items %}
                <ul class="item-list">
                    {% for item in cart_items %}
                    {% comment %} <p>id: {{ item.id }}</p> {% endcomment %}
                        <li class="item">
                            {% comment %} <input type="checkbox" class="item-checkbox" onclick="updateTotalAndCount()"> {% endcomment %}
                            <input type="checkbox" class="item-checkbox" onclick="updateTotalAndCount()" data-item-id="{{ item.id }}">

                            <div class="details">
                    
                                <h3>{{ item.telefon.model }}</h3>
                                {% comment %} <p>id: {{ item.telefon.id }}</p> {% endcomment %}
                                <p>Producător: {{ item.telefon.producator }}</p>
                                <p class="details-descriere">Descriere: {{ item.telefon.descriere }}</p>
                                <p class="item-price">Price: {{ item.telefon.price }} €</p>
                            </div>
                            <div class="images">
                                {% if item.telefon.images_set.all %}
                                    <div class="image-gallery">
                                        {% for image in item.telefon.images_set.all %}
                                            <img src="{{ image.image.url }}" alt="Imagine Telefon">
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    <p>Nu există imagini disponibile pentru acest telefon.</p>
                                {% endif %}
                            </div>
                            <div class="counter-container">
                                <button class="button-details" onclick="decrementCount(this)">-</button>
                                <span class="counter-value">1</span>
                                <button class="button-details" onclick="incrementCount(this)">+</button>
                            </div>
                            <button class="button-delete" onclick="deleteToCart({{ item.telefon.id }}, this)">X</button>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>Cosul este gol.</p>
            {% endif %}
        </div>

        <div class="Payment">
            <div class="Detali-plata">
                <p class="titlu">Summary</p>
                <p>Total: <span id="total-price">0</span> €</p>
                <p>In lei: <span id="total-price-lei">0</span> lei</p>
                <button class="b" id="checkout-button" onclick="checkout()">Checkout (0)</button>
            </div>

            <div class="Cart-image">
                <img src="{% static 'css/card.png' %}" alt="Imagine  Modern">
            </div>
        </div>
    </div>

    <footer>
        {% include 'footer.html' %}
        </footer>

        
 
</body>
</html>

telefon/templates/footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Website cu Știri în Footer</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/footer.css' %}">
</head>
<body>
    
    <footer>
        <div class="news">
            <div class="news-item">
                <a href="/">Telefon</a>
                    </div>
            <div class="news-item">
                <a href="/about">About</a>                
            </div>
            <div class="news-item">
                <a href="/laptop">Laptop</a>
               </div>
               <div class="news-item">
                <li><a href="/laptop/contact">Contact</a></li>
               </div>
            <div class="news-item">
             <a href="/cos"><i class="fas fa-shopping-cart"></i></a>
            </div>
        </div>
        <p>&copy; 2024 Numele Companiei. Toate drepturile rezervate.</p>
    </footer>
</body>
</html>

telefon/templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <title>List of Phones</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
    
</head>
<body>
    <header>
        <div class="containerr">
            <nav>
                <ul>
                    <li><a href="/">Telefon</a></li>
                    <li><a href="/about">About</a></li>
                    <li><a href="/laptop">Laptop</a></li>
                    <li><a href="/laptop/contact">Contact</a></li>
                    <li><a href="/cos"><i class="fas fa-shopping-cart"></i></a></li>
                </ul>
            </nav>
        </div>
    </header>

   

    
</body>
</html>

telefon/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List of Phones</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/magazin/magaz.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/magazin/search.css' %}">
    <script src="{% static 'js/add_cart.js' %}"></script>
</head>
<body>
    <header>
        <h1>List of Phones</h1>
        {% include 'header.html' %}
    </header>
    <div class="search-telefon">
        <form method="GET" action="{% url 'search' %}">
            <div class="field-search">
                <div class="control-search">
                    <input class="input-search" type="text" placeholder="Find a telefon" name="q">
                    <button class="button is-info-search">Search</button>
                </div>
            </div>

        </form>
    </div>

    {% if request.GET.q %}
        <p class="mesaj-search">
        După căutarea '{{ request.GET.q }}' au fost găsite {{ telefons|length }} produse.
        </p>
    {% endif %}



    <div class="container-telefon">
        {% if telefons %}
            {% for telefon in telefons %}
                <div class="phone">
                    <div class="details">
                        <h3>{{ telefon.model }}</h3>
                        <p>Producător: {{ telefon.producator }}</p>
                        <p>Procesor: {{ telefon.procesor }}</p>
                        <p>Descriere: {{ telefon.descriere }}</p>
                        <p>Price: {{ telefon.price }} €</p>
                    </div>
                    <div class="images">
                        {% if telefon.images_set.all %}
                            <div class="image-gallery">
                                {% for image in telefon.images_set.all %}
                                    <img src="{{ image.image.url }}" alt="Imagine Telefon">
                                {% endfor %}
                            </div>
                        {% else %}
                            <p>Nu există imagini disponibile pentru acest telefon.</p>
                        {% endif %}
                        <ul>
                            <button class="button-adaug" data-quantity="1" onclick="addToCart({{ telefon.id }}, this)">Adauga in cos</button>
                        </ul>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>

    <footer>
        {% include 'footer.html' %}
    </footer>
</body>
</html>

telefon/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Succes</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/magazin/success.css' %}">
</head>
<body>
    <header>
        <h1>Plata a fost efectuată cu succes!</h1>
        {% include 'header.html' %}
    </header>
    <div class="content">
        <p>Vă mulțumim pentru cumpărături!</p>
        <a href="/">Înapoi la pagina principală</a>
    </div>
    <footer>
        {% include 'footer.html' %}
    </footer>
</body>
</html>